apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-project-deployment
spec:
  selector:
    matchLabels:
      app: ci-cd-project
  replicas: 2
  template:
    metadata:
      labels:
        app: ci-cd-project
    spec:
      containers:
        - name: ci-cd-project
          image: okon03/ci_cd_hub:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ci-cd-project-ssvc
spec:
  selector:
    app: ci-cd-project
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
